# Generated by Django 5.0.4 on 2024-07-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_restaurantreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantReview',
            new_name='RegularRestaurantReview',
        ),
    ]
