# Generated by Django 5.0.4 on 2024-07-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_menureview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcriticrestaurantreview',
            options={'verbose_name': 'Food Critic Review', 'verbose_name_plural': 'Food Critic Reviews'},
        ),
    ]
