# Generated by Django 5.0.4 on 2024-06-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_capital',
            field=models.BooleanField(default=False),
        ),
    ]
