# Generated by Django 5.0.6 on 2024-06-24 05:27
import random
from django.db import migrations


def add_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    all_products = Product.objects.all()
    all_barcodes = random.sample(
        range(100000000, 1000000000),
        len(all_products)
    )
    for i in range(len(all_products)):
        product = all_products[i]
        product.barcode = all_barcodes[i]
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_product_category_alter_product_supplier'),
    ]

    operations = [
    ]
