# Generated by Django 5.0.4 on 2024-07-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_owner_car_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=1999),
            preserve_default=False,
        ),
    ]
